addSbtPlugin("io.get-coursier"   % "sbt-coursier" % "1.0.0-RC12")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "1.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.18")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalajs-bundler" % "0.5.0")
