addSbtPlugin("io.get-coursier"   % "sbt-coursier" % "1.0.1")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "2.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.scala-js"      % "sbt-scalajs"  % "0.6.29")
