name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: npm install jsdom
      - run: sbt +test
      - run: sbt 'set every scalaJSStage := FullOptStage' +test
